"""empty message

Revision ID: 847479ce3e5e
Revises: 05f18f8ec009
Create Date: 2025-02-26 14:05:22.769618

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '847479ce3e5e'
down_revision = '05f18f8ec009'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.alter_column('price',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=2),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.alter_column('price',
               existing_type=sa.Float(precision=2),
               type_=sa.REAL(),
               existing_nullable=False)

    # ### end Alembic commands ###
